name: "[Compute Platform] Integration Tests"
# Run tests for Compute Platform after merge and as a cron job
on:
  schedule: # Trigger for scheduled integration tests
    - cron: '*/2 * * * *' # Runs scheduled integration tests
  workflow_dispatch: # Manual trigger
    inputs:
      environment:
        description: "Choose the environment to run tests on (e.g., dev, prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - stage
          - prod
      test_suite:
        description: "Specify which tests to run (e.g., on_demand, integration)"
        required: true
        default: "Integration-Tests"
        type: choice
        options:
          - pluto_integration_tests
          - pluto_ondemand_tests
          - Autorecovery_integration_test

jobs:
  Autorecovery_integration_tests: # Workflow for Autorecovery_integration_tests
    name: 'Autorecovery Integration Tests'
    if: github.event_name.schedule == '*/2 * * * *' || (github.event_name == 'workflow_dispatch' && github.event.inputs.test_suite == 'Autorecovery-Integration-Test' && github.event.inputs.environment == 'stage')
    runs-on:
      - scale-set-runners-cpu
    steps:
      - name: Checkout project
      - name: Setup venv
        
      - name: Run tests
        run: |
          if [ "${{ github.event.inputs.environment }}" == "" ]; then
            if [ "${{ github.event.schedule }}" == "0 */12 * * *" ]; then
                PLUTO_ENV=stage
                echo 'stage'
            fi
          else
              PLUTO_ENV=${{ github.event.inputs.environment }}
          fi
          echo "PLUTO_ENV=$PLUTO_ENV" >> $GITHUB_ENV
      - name: Send notification to Slack on failure
        if: ${{ failure() }}
        run: |
            echo "GitHub Step Summary File:"
          
